// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return android;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
      return web;
      case TargetPlatform.windows:
        return macos;
      case TargetPlatform.linux:
        return windows;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiYU09ALhj3jghLRoAz9m-5U6IsJg-k2E',
    appId: '1:714028074822:android:1a304c417d916712500747',
    messagingSenderId: '714028074822',
    projectId: 'eventtrack-158c3',
    storageBucket: 'eventtrack-158c3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArvZZsJPSlskNY2ovC4ovF0zueHpFZ0ug',
    appId: '1:714028074822:ios:88026d8e33150dda500747',
    messagingSenderId: '714028074822',
    projectId: 'eventtrack-158c3',
    storageBucket: 'eventtrack-158c3.firebasestorage.app',
    iosBundleId: 'com.example.eventTrack',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFh8nDoCXiiDOcg0GkBXolklJlHuflDpo',
    appId: '1:714028074822:web:b2e24c8ff149d479500747',
    messagingSenderId: '714028074822',
    projectId: 'eventtrack-158c3',
    authDomain: 'eventtrack-158c3.firebaseapp.com',
    storageBucket: 'eventtrack-158c3.firebasestorage.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArvZZsJPSlskNY2ovC4ovF0zueHpFZ0ug',
    appId: '1:714028074822:ios:88026d8e33150dda500747',
    messagingSenderId: '714028074822',
    projectId: 'eventtrack-158c3',
    storageBucket: 'eventtrack-158c3.firebasestorage.app',
    iosBundleId: 'com.example.eventTrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmFQaBsD-pm0StVr-pxio6rmls1cjYR5c',
    appId: '1:778009533457:web:8672bd03fda0252dd125b0',
    messagingSenderId: '778009533457',
    projectId: 'psu-event-monitor',
    authDomain: 'psu-event-monitor.firebaseapp.com',
    storageBucket: 'psu-event-monitor.firebasestorage.app',
    measurementId: 'G-QC4THHMLWB',
  );

}